# Dependencies
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:           pretty

# Setup
url:                 http://bluesh55.github.io/

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             ''

title:               Bluesh

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

description: "DEV"

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
sidebar_description: |
  Location: Seoul, Korea  
  Name: Seunghwan Oh  
  Email: bluesh55@naver.com  

# The tags listed as entries in the sidebar
sidebar_tags:        [dev]

# Fallback image and color if not overwritten for tag or post
image:               '/public/img/cat.jpg'
color:               '#AC4142'

# Fonts
font:                '"SpoqaHanSans", "sans-serif"'

# About yourself
author:
  name:              '오승환 | Seunghwan Oh'

  # This photo will be used in the about section
  photo:             /public/img/profile.jpeg
  photo2x:           /public/img/profile.jpeg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about: |
    스타트업에서 일하는 것을 좋아하는 평범한 개발자입니다.  
    뭔가를 배우는것을 좋아하는 편이고 특히 객체 지향, 아키텍처, 클린 코드 등에 관심이 많습니다.  
    넓고 얕은 것 보다 좁고 깊게 배우는 것을 지향합니다.  


  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    facebook:        100003308714951
    # twitter:         _username_
    # google:          _number_
    # vk:              _username_
    # youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    instagram:       bluesh55
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    github:          bluesh55
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
google_analytics_id: 'UA-84736400-1'

# Setting a disqus subdomain will enable the comment section
disqus: bluesh55

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
